name: remove eks cluster and node groups

on:
  workflow_dispatch:
  
jobs:
  remove_eks_node_groups:
    runs-on: ubuntu-latest
    steps:
    - name: install and verify eksctl cli
      run: |
        curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
        mv /tmp/eksctl /usr/local/bin
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: remove cluster node groups
      run: |
        eksctl delete nodegroup --cluster=eksdemo1 --name=eksdemo1-ng-public1 --drain=false

  wait:
    runs-on: ubuntu-latest
    needs:
      - remove_eks_node_groups
    steps:
    - name: wait for 5 minutes
      run: |
        sleep 300

  remove_eks_cluster:
    runs-on: ubuntu-latest
    needs:
      - wait
    steps:
      - name: install and verify eksctl cli
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          mv /tmp/eksctl /usr/local/bin
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: remove cluster
        run: | 
          eksctl delete cluster --name eksdemo1
