name: Build and deploy JAR app to AWS ECR - tripblogger-api-spring

on:
  workflow_dispatch:
  
jobs:
  setup_eks_cluster:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: verify aws install
      run: |
        which aws 
        aws --version
      
#     - name: 
